In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
prophet=pd.read_csv(r"C:\Users\Top Prix\OneDrive\New folder\Thesis_Project\notebooks\prophet_walkforward_predictions.csv", parse_dates=["timestamp"], index_col="timestamp")

In [4]:
prophet.head()

                           actual     predicted
timestamp
2025-07-01 00:00:00  15106.036458  14918.457780
2025-07-01 01:00:00  14431.000000  14599.624114
2025-07-01 02:00:00  13858.500000  14441.313183
2025-07-01 03:00:00  13106.500000  14342.752642
2025-07-01 04:00:00  12483.250000  14227.444591

In [5]:
holtwinter=pd.read_csv(r"C:\Users\Top Prix\OneDrive\New folder\Thesis_Project\notebooks\hw_predictions.csv", parse_dates=["timestamp"], index_col="timestamp")

In [6]:
holtwinter.head()

                           actual     predicted
timestamp
2025-07-01 00:00:00  15106.036458  15428.480735
2025-07-01 01:00:00  14431.000000  14829.281494
2025-07-01 02:00:00  13858.500000  14319.141889
2025-07-01 03:00:00  13106.500000  13942.233823
2025-07-01 04:00:00  12483.250000  13412.895503

In [7]:
sarima=pd.read_csv(r"C:\Users\Top Prix\OneDrive\New folder\Thesis_Project\notebooks\sarima_walkforward_predictions.csv", parse_dates=["timestamp"], index_col="timestamp")

In [8]:
sarima.head()

                           actual     predicted
timestamp
2025-07-01 00:00:00  15106.036458  15378.864103
2025-07-01 01:00:00  14431.000000  14676.529835
2025-07-01 02:00:00  13858.500000  14075.611436
2025-07-01 03:00:00  13106.500000  13607.126959
2025-07-01 04:00:00  12483.250000  13059.111327

In [9]:
rf=pd.read_csv(r"C:\Users\Top Prix\OneDrive\New folder\Thesis_Project\notebooks\rf_walkforward_predictions.csv", parse_dates=["timestamp"], index_col="timestamp")

In [10]:
rf.head()

                           actual     predicted
timestamp
2025-07-01 00:00:00  15106.036458  13199.824272
2025-07-01 01:00:00  14431.000000  12862.640337
2025-07-01 02:00:00  13858.500000  12173.528104
2025-07-01 03:00:00  13106.500000  11740.275031
2025-07-01 04:00:00  12483.250000  11319.812590

In [11]:
xgboost=pd.read_csv(r"C:\Users\Top Prix\OneDrive\New folder\Thesis_Project\notebooks\xgb_predictions.csv", parse_dates=["timestamp"], index_col="timestamp")

In [12]:
xgboost.head()

                           actual  predicted
timestamp
2025-07-01 00:00:00  15106.036458  13128.392
2025-07-01 01:00:00  14431.000000  12814.236
2025-07-01 02:00:00  13858.500000  12222.107
2025-07-01 03:00:00  13106.500000  11827.756
2025-07-01 04:00:00  12483.250000  11614.954

In [13]:
lstm=pd.read_csv(r"C:\Users\Top Prix\OneDrive\New folder\Thesis_Project\notebooks\lstm_predictions.csv", parse_dates=["timestamp"], index_col="timestamp")

In [14]:
lstm.head()

                           actual  predicted
timestamp
2025-07-01 00:00:00  15106.036458  12994.574
2025-07-01 01:00:00  14431.000000  12572.209
2025-07-01 02:00:00  13858.500000  11520.877
2025-07-01 03:00:00  13106.500000  11515.020
2025-07-01 04:00:00  12483.250000  10835.635

Random Forest Errors

In [15]:
error_rf=rf["actual"]-rf["predicted"]

In [16]:
error_rf.head()

timestamp
2025-07-01 00:00:00    1906.212186
2025-07-01 01:00:00    1568.359663
2025-07-01 02:00:00    1684.971896
2025-07-01 03:00:00    1366.224969
2025-07-01 04:00:00    1163.437410
dtype: float64

XGBOOST Errors

In [17]:
error_xgb=xgboost["actual"]-xgboost["predicted"]
error_xgb.head()

timestamp
2025-07-01 00:00:00    1977.644458
2025-07-01 01:00:00    1616.764000
2025-07-01 02:00:00    1636.393000
2025-07-01 03:00:00    1278.744000
2025-07-01 04:00:00     868.296000
dtype: float64

LSTM Errors

In [18]:
error_lstm=lstm["actual"]-lstm["predicted"]
error_lstm.head()

timestamp
2025-07-01 00:00:00    2111.462458
2025-07-01 01:00:00    1858.791000
2025-07-01 02:00:00    2337.623000
2025-07-01 03:00:00    1591.480000
2025-07-01 04:00:00    1647.615000
dtype: float64

SARIMA Errors

In [19]:
error_sarima=sarima["actual"]-sarima["predicted"]
error_sarima.head()

timestamp
2025-07-01 00:00:00   -272.827645
2025-07-01 01:00:00   -245.529835
2025-07-01 02:00:00   -217.111436
2025-07-01 03:00:00   -500.626959
2025-07-01 04:00:00   -575.861327
dtype: float64

HW Errors

In [20]:
error_hw=holtwinter["actual"]-holtwinter["predicted"]
error_hw.head()

timestamp
2025-07-01 00:00:00   -322.444277
2025-07-01 01:00:00   -398.281494
2025-07-01 02:00:00   -460.641889
2025-07-01 03:00:00   -835.733823
2025-07-01 04:00:00   -929.645503
dtype: float64

Prophet Errors

In [21]:
error_prophet=prophet["actual"]-prophet["predicted"]
error_prophet.head()

timestamp
2025-07-01 00:00:00     187.578679
2025-07-01 01:00:00    -168.624114
2025-07-01 02:00:00    -582.813183
2025-07-01 03:00:00   -1236.252642
2025-07-01 04:00:00   -1744.194591
dtype: float64

DM TEST

In [22]:
from statsmodels.stats.diagnostic import acorr_ljungbox
from scipy import stats

def dm_test(e1, e2):
    d = e1**2 - e2**2  # loss differential
    n = len(d)
    mean_d = d.mean()
    acov = np.cov(d)  # variance
    dm_stat = mean_d / np.sqrt(acov / n)
    p_value = 2 * stats.norm.cdf(-abs(dm_stat))
    return dm_stat, p_value

In [23]:
competitors = {
    "SARIMA": error_sarima,
    "XGBoost": error_xgb,
    "LSTM": error_lstm,
    "HW": error_hw,
    "Prophet": error_prophet
}

for name, e in competitors.items():
    stat, p = dm_test(error_rf, e)
    print(f"DM(RF vs {name}): stat={stat:.4f}, p={p:.4f}")

DM(RF vs SARIMA): stat=-4.2500, p=0.0000
DM(RF vs XGBoost): stat=-2.4058, p=0.0161
DM(RF vs LSTM): stat=0.4724, p=0.6367
DM(RF vs HW): stat=-11.3904, p=0.0000
DM(RF vs Prophet): stat=-26.0091, p=0.0000

In [24]:
def dm_test_mse(e1, e2):
    d = np.abs(e1) - np.abs(e2)  # loss differential
    n = len(d)
    mean_d = d.mean()
    acov = np.cov(d)  # variance
    dm_stat = mean_d / np.sqrt(acov / n)
    p_value = 2 * stats.norm.cdf(-abs(dm_stat))
    return dm_stat, p_value

In [25]:
competitors = {
    "SARIMA": error_sarima,
    "XGBoost": error_xgb,
    "LSTM": error_lstm,
    "HW": error_hw,
    "Prophet": error_prophet
}

for name, e in competitors.items():
    stat, p = dm_test_mse(error_rf, e)
    print(f"DM(RF vs {name}): stat={stat:.4f}, p={p:.4f}")

DM(RF vs SARIMA): stat=-1.6137, p=0.1066
DM(RF vs XGBoost): stat=-6.2164, p=0.0000
DM(RF vs LSTM): stat=-1.4587, p=0.1447
DM(RF vs HW): stat=-13.9394, p=0.0000
DM(RF vs Prophet): stat=-34.3990, p=0.0000